package com.davinchicoder.kafka_cero_a_experto.user.infrastructure.event.mapper;

import com.davinchicoder.kafka_cero_a_experto.autogenerated.events.user.*;
import com.davinchicoder.kafka_cero_a_experto.common.infrastructure.event.util.MapperUtils;
import com.davinchicoder.kafka_cero_a_experto.user.application.created.UserCreatedCommand;
import com.davinchicoder.kafka_cero_a_experto.user.application.deleted.UserDeletedCommand;
import com.davinchicoder.kafka_cero_a_experto.user.application.emailUpdated.UserEmailUpdatedCommand;
import com.davinchicoder.kafka_cero_a_experto.user.domain.event.UserDeactivatedDomainEvent;
import com.davinchicoder.kafka_cero_a_experto.user.domain.event.UserVerificationRequestedDomainEvent;
import org.mapstruct.Mapper;
import org.mapstruct.MappingConstants;
import org.mapstruct.ReportingPolicy;

@Mapper(componentModel = MappingConstants.ComponentModel.SPRING, unmappedTargetPolicy = ReportingPolicy.ERROR)
public interface UserEventMapper extends MapperUtils {

    UserCreatedCommand mapToUserCreatedCommand(UserCreatedEvent event);

    UserEmailUpdatedCommand mapToUserEmailUpdatedCommand(UserEmailUpdatedEvent event);

    UserDeletedCommand mapToUserDeletedCommand(UserDeletedEvent event);
 
    UserDeactivatedEvent mapToUserDeactivatedEvent(UserDeactivatedDomainEvent event);

    UserVerificationRequestedEvent mapToUserVerificationRequestedEvent(UserVerificationRequestedDomainEvent event);

}
