package com.davinchicoder.kafka_cero_a_experto.user.infrastructure.api;

import com.davinchicoder.kafka_cero_a_experto.autogenerated.events.user.UserCreatedEvent;
import com.davinchicoder.kafka_cero_a_experto.common.infrastructure.event.producer.KafkaProducer;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/users")
@RequiredArgsConstructor
public class UserController {

    private final KafkaProducer kafkaProducer;

    @GetMapping("/create")
    public void createUser() {
        System.out.println("Creating user");
        UserCreatedEvent userCreatedEvent = UserCreatedEvent.newBuilder()
                .setId(1L)
                .setFirstname("David")
                .setLastname("Jimenez")
                .setEmail("support@davichicoder.dev")
                .setRole("USER")
                .setTimestamp(System.currentTimeMillis())
                .build();

        kafkaProducer.send("user.events", userCreatedEvent);
    }


}
