package com.davinchicoder.kafka_cero_a_experto.user.infrastructure.event.consumer.specific;

import com.davinchicoder.kafka_cero_a_experto.autogenerated.events.user.UserEmailUpdatedEvent;
import com.davinchicoder.kafka_cero_a_experto.common.application.Mediator;
import com.davinchicoder.kafka_cero_a_experto.common.infrastructure.event.consumer.EventSpecificConsumer;
import com.davinchicoder.kafka_cero_a_experto.user.application.emailUpdated.UserEmailUpdatedCommand;
import com.davinchicoder.kafka_cero_a_experto.user.infrastructure.event.mapper.UserEventMapper;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.messaging.Message;
import org.springframework.stereotype.Component;

@Component
@Slf4j
@RequiredArgsConstructor
public class UserEmailUpdatedSpecificConsumer implements EventSpecificConsumer<UserEmailUpdatedEvent> {

    private final Mediator mediator;
    private final UserEventMapper userEventMapper;

    @Override
    public void accept(Message<UserEmailUpdatedEvent> genericRecordMessage) {
        log.info("UserEmailUpdatedSpecificConsumer message: {}", genericRecordMessage.toString());
        UserEmailUpdatedCommand command = userEventMapper.mapToUserEmailUpdatedCommand(genericRecordMessage.getPayload());
        mediator.dispatch(command);
    }

    @Override
    public String getSchema() {
        return UserEmailUpdatedEvent.getClassSchema().getFullName();
    }
}
